### ISSUE TITLE
Amazing Demo. Clean Code. Thanks for Sharing

### ISSUE THREAD

**Issue by SopMar** [jangyoun/android-recyclerview-with-header#1]
Hello Jangyoun. I just downloaded your demo code and experienced on device, and found this one just best.

I am trying to make a small modification, like: In Play Store now Google is showing 7 horizontal items in place of  Slider (as they were using View Pager earlier).

But, I tried my best to show header data as Horizontal Items instead of Slider... But Unfortunately did not get success...

So please make this small change and share updated code with us, so we can learn that way as well.
I have to Submit an assignment in which I have to design Google Play Store like Home Page...

**Comment by jangyoun** [comment]
Hi @SopMar 

I recommend multiviewpager instead of ViewPager.
If you use multiviewpager, you make UI view like PlayStore
https://github.com/Pixplicity/MultiViewPager
